CREATE TABLE sellers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_name VARCHAR(255) NOT NULL,
    contact_info VARCHAR(255) NOT NULL UNIQUE,
    registration_date TIMESTAMP NOT NULL
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    payment_type VARCHAR(50) NOT NULL,
    transaction_date TIMESTAMP NOT NULL,

    CONSTRAINT fk_transaction_seller
        FOREIGN KEY (seller_id)
        REFERENCES sellers(id)
        ON DELETE CASCADE
);