spring:
  application:
    name: ShiftCRM
  datasource:
    url: jdbc:postgresql://localhost:5432/shiftcrm_db
    username: postgres
    password: 123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
